name: CI
on: [push, pull_request]
env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  Configuration: Release
  PagesCname: phalanx.tools
defaults:
  run:
    shell: pwsh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - run: dotnet --info
      - run: dotnet tool restore
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build

      - name: Publish
        run: dotnet publish src/Phalanx.App --output ./.build/pub -p:GHPages=true -p:GHPagesBase=https://${{ env.PagesCname }}

      - name: Push gh-pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build/pub/wwwroot
          cname: ${{ env.PagesCname }}
          force_orphan: true
