name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
      - "**/*.yml"
env:
  DOTNET_NOLOGO: 1
  Configuration: Release
  PagesCname: www.phalanx.tools
defaults:
  run:
    shell: pwsh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
      - run: dotnet --info
      - run: dotnet tool restore
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build
      - run: dotnet format --no-restore --verify-no-changes --verbosity normal

  deploy_main:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
      - run: dotnet --info
      - run: dotnet tool restore

      - name: Publish
        run: dotnet publish src/Phalanx.App --output ./.build/pub -p:GHPages=true -p:GHPagesBase=https://${{ env.PagesCname }}

      - name: Push gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build/pub/wwwroot
          cname: ${{ env.PagesCname }}
          force_orphan: true
