name: CI
on:
  push:
env:
  DOTNET_NOLOGO: 1
  Configuration: Release
  PagesCname: www.phalanx.tools
defaults:
  run:
    shell: pwsh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - run: dotnet --info
      - run: dotnet tool restore
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build
      # IL2026 Using member T.M which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. T's dependent types may have their members trimmed. Ensure all required members are preserved.
      # IL2026 is triggered because dotnet format probably doesn't support interceptors
      - run: dotnet format --no-restore --verify-no-changes --verbosity normal --exclude-diagnostics IL2026

  deploy_main:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - run: dotnet --info
      - run: dotnet tool restore

      - name: Publish
        run: dotnet publish src/Phalanx.App --output ./artifacts/publish-content -p:GHPages=true -p:GHPagesBase=https://${{ env.PagesCname }}

      - name: Push gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./artifacts/publish-content/wwwroot
          cname: ${{ env.PagesCname }}
          force_orphan: true
