name: PR CD
on:
  workflow_run:
    workflows: [PR CI]
    types: [completed]
defaults:
  run:
    shell: pwsh
jobs:
  deploy_pr:
    name: Deploy PR webapp
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    env:
      wwwroot_path: ./wwwroot/
    steps:
      - uses: actions/checkout@v3

      - name: Download webapp from workflow artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          name: pr-data
          run_id: ${{ github.event.workflow_run.id }}

      - name: Prepare artifacts
        uses: Amadevus/pwsh-script@v2
        with:
          script: |
            Expand-Archive webapp.zip $env:wwwroot_path
            $event = Get-Content event.json -Raw | ConvertFrom-Json
            Set-ActionVariable pr_number $event.pull_request.number

      - name: Checkout PR for Azure SWA action
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ env.pr_number }}/merge
          clean: false

      - name: Add staticwebapp config
        env:
          config_content: |
            {
              "navigationFallback": {
                "rewrite": "/index.html",
                "exclude": ["/*.{png,jpg,gif,ico,svg,js,json,dll,css}", "/css/*"]
              }
            }
        run: |
          $env:config_content > $env:wwwroot_path/staticwebapp.config.json

      - name: Deploy Azure Static Webapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          skip_app_build: true
          skip_api_build: true
          app_location: ${{ env.wwwroot_path }}
          output_location: ${{ env.wwwroot_path }}
